version: '3'

services:
  postgres:
    container_name: task_postgres
    image: postgres:12.3
    ports:
      - 5490:5432
    environment:
      - POSTGRES_DB=osome
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
